### ISSUE TITLE
Docker GPU problem

### ISSUE THREAD

**Issue by mhelal** [ViLab-UCSD/PhotoScene#1]
Hello

I am having problems running GPU from docker as follows:

```
$ bash scripts/run_docker_interactive.sh

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.
```

I followed many online workarounds, but nothing worked so far. Last attempt was following this link https://discuss.linuxcontainers.org/t/docker-with-gpu-support-in-unprivileged-lxd-container/5783/2 :

`after the docker starts, map GPU buses /proc/driver/nvidia/gpus/xxxxxx from the host to the LXD container. The xxxxx pci buses should be those of the GPUs passed through from LXD to docker. The needed pci buses can be identified with nvidia-smi.

`

I installed lxc, but I do not know how to map GPU to busto LXD container, and not sure if your project uses LXD container or is useful at all.

Any help is very appreciated, 

Thank you, 

Manal

**Comment by yuyingyeh** [comment]
Hi Manal,

Thanks for your interest in our work! Have you tried to modify `/etc/nvidia-container-runtime/config.toml` for the entry under `[nvidia-container-cli]` to `no-cgroups = true`?

Yu-Ying

**Comment by yuyingyeh** [comment]
Close for inactivity. Please reopen the issue if you still have questions.
