### ISSUE TITLE
How to download Substance Designer All builds

### ISSUE THREAD

**Issue by HospitableHost** [ViLab-UCSD/PhotoScene#2]
Thanks for your excellent work. I have some trouble downloading Substance Designer All builds. There is no this app in the website you offered, and I asked the helper of adobe, they still give me nothing about the downloading link.
Looking to your reply, best wishes.

And I have searched all websites of adobe, still nothing.

**Comment by yuyingyeh** [comment]
Hi @HospitableHost ,

Thanks for your interest in our work! I don't know why Adobe removed their link to the toolkit, but you might want to reach out to our co-authors who are affiliated with Adobe to see if they can help. Thank you.

Yu-Ying

**Comment by HospitableHost** [comment]
Hi @yuyingyeh ,
Thanks for your help, what operating system are you using (to meet the system requirements of Substance_Designer-11.1.2-4593-linux-x64-standard.rpm)? Is it Ubuntu18?

**Comment by yuyingyeh** [comment]
Hii @HospitableHost ,

It should work in Ubuntu18 as this is the version used in the provided docker image. Thank you.

**Comment by yuyingyeh** [comment]
According to Diffmat's author response (https://github.com/mit-gfx/diffmat/issues/5#issuecomment-1780382000), [Adobe Substance 3D](https://www.adobe.com/creativecloud/3d-ar.html) is now an alternative to obtain the sbscooker and sbsrender.
