### ISSUE TITLE
Renderer issue: pure virtual method called

### ISSUE THREAD

**Issue by HospitableHost** [ViLab-UCSD/PhotoScene#3]
Thanks for your excellent work @yuyingyeh. I have some trouble with the renderer. 
My GPU is RTX3090 with cuda 11.1 and **I have successfully compiled the renderer**. (I change sm_30 to sm_64 in the cmake file to avoid compile error.)
The cmd I use: python3 photoscene/preprocess.py --config configs/total3d/Total_246.yaml
The core dumped issue I met:
![image](https://github.com/ViLab-UCSD/PhotoScene/assets/44576391/2ca90ace-9338-451a-ab7b-f5372f60f753)
I have locate the code which leads to this issue:  (in photoscene/utils/render.py _renderPass_ Function)
![image](https://github.com/ViLab-UCSD/PhotoScene/assets/44576391/f2b401f0-6abd-4f70-b236-5235f8288f8c)
So I print the cmd: 
`third_party/OptiX_Renderer/OptixRenderer_MatPart/src/bin/optixRenderer -f /mnt/data2/dangziqiang2/ProceduralMaterial/PhotoScene/outputs/total3d/scene246/preprocess/xmlInit/main.xml -c /mnt/data2/dangziqiang2/ProceduralMaterial/PhotoScene/outputs/total3d/scene246/preprocess/cameras/cam_all.txt -o /mnt/data2/dangziqiang2/ProceduralMaterial/PhotoScene/outputs/total3d/scene246/preprocess/renderInit/partId/im.hdr -m 7 --modelIdFile /mnt/data2/dangziqiang2/ProceduralMaterial/PhotoScene/outputs/total3d/scene246/preprocess/meshes/models.txt --seed 0 > /mnt/data2/dangziqiang2/ProceduralMaterial/PhotoScene/logs/renderPartId.txt`

Please help me, I don't know where I went wrong. Thanks very much for your reply!

**Comment by yuyingyeh** [comment]
Hi @HospitableHost ,

Thanks for trying out the renderer. My GPU version is 2080Ti, which is older than yours (3090). Maybe you can try to run it using older GPU cards and see if it works. Thank you.

**Comment by yuyingyeh** [comment]
As confirmed in https://github.com/ViLab-UCSD/PhotoScene/issues/4#issuecomment-1836188697, this is a GPU-related issue. Using older GPU (e.g. 2080Ti) can solve the issue.
