### ISSUE TITLE
 Inquiry Regarding Missing "layout.mat" File in the Codebase

### ISSUE THREAD

**Issue by yhhxt** [ViLab-UCSD/PhotoScene#4]
![image](https://github.com/ViLab-UCSD/PhotoScene/assets/55875788/8e761b9e-87e8-4ef6-8cee-eef78232c6c7)
Hello, I've been encountering an issue while running the code, specifically a missing "layout.mat" file.  Despite searching through the file system, I couldn't locate it. In the code, it is referenced as an input, and its  location is within the "outputs" folder. Does this mean that this is the output of a submodule?

I observed that during the project clone, I faced network issues, and as a result, the "third_party" submodule appears to be empty.    Could this be the reason behind the submodule-related problems and the absence of the "layout.   mat" file as its output?

I appreciate any insights or guidance you can provide to help resolve this issue.

**Comment by yuyingyeh** [comment]
Hi @yhhxt ,

Thanks for your question. You need to also clone the submodules as well. In this error, it seems that `third_party/Total3D` is not cloned successfully so my script cannot generate the files under `data/total3d/outputs`. Please make sure all the submodules are cloned completely. Thank you.

**Comment by yhhxt** [comment]
Thank you very much for your response. Yesterday, I attempted to clone all the submodules again, and now it can produce partial results. However, some outputs are still missing. I noticed that the three folders (uvCoord, normal, partid)  located under `preprocess/renderInit` are all empty. In the code, these three components are implemented by OptiXRender, and their output results are empty. I'm unsure whether this is a compilation issue with OptiXRender or an installation problem with OptiX. The error message is as shown in the attached image.
![image](https://github.com/ViLab-UCSD/PhotoScene/assets/55875788/ef18ad2e-6d32-46b1-b91a-06846bfaaf01)

**Comment by yuyingyeh** [comment]
It seems that this issue is similar to https://github.com/ViLab-UCSD/PhotoScene/issues/3#issuecomment-1776288865

I wonder if you're using newer GPUs, e.g. 30 or 40 series. Unfortunately, our OptiX version is quite old and we only test it on 2080Ti GPU. Sorry for this inconvenience.

**Comment by yhhxt** [comment]
Yes, the graphics card I'm currently using is the RTX 3090.   This might be one of the reasons.   Thank you very much for your response.

**Comment by yhhxt** [comment]
The issue seems to be related to the graphics card. I did not encounter this error when replicating the process with the 2080ti. It appears to be an incompatibility between OptiX and the graphics card. Thank you for your professional advice.@yuyingyeh
