### ISSUE TITLE
Inquiry About Increasing Material Resolution Beyond 256

### ISSUE THREAD

**Issue by zhanghe3z** [ViLab-UCSD/PhotoScene#5]
Nice work on the project! I'm really impressed with what you've achieved here. I have a question regarding the resolution of optimized materials. Currently, the code seems to only output materials at a 256 resolution. However, from what I observed in the teaser images, the resolution appears to be quite high. Could you guide me on how to increase the resolution of these materials beyond 256? How can the resolution of optimized materials be increased? Any tips or code modifications that would allow achieving higher-resolution outputs would be greatly appreciated. Looking forward to your response, and thanks again for your fantastic work!

**Comment by yuyingyeh** [comment]
Hi @zhanghe3z ,

Thanks for the question! You can modify the config file to achieve this. For example, you can increase the `matRes` from 8 to 9 (which means 2^9=512).
https://github.com/ViLab-UCSD/PhotoScene/blob/67c93583adbaf14b7834e66b19541063f6046011/configs/base.yaml#L38

**Comment by zhanghe3z** [comment]
@yuyingyeh  Thank you for your response.
